- hosts: masternode
  check_mode: yes
# , workernodes
  # gather_facts: no
  vars:
  # pre_tasks:

  tasks:

  roles:
    - install-kube

# - hosts: masternodes
#   vars:
#
#   roles:
#     - setup-kube-master

# - hosts: workernodes
#   vars:
#
#   roles:
#     - setup-kube-worker
