- hosts: masternodes
  gather_facts: no
  vars:

  # pre_tasks:


  tasks:

  roles:
    - download-artifacts
    - setup-kube-master

# - hosts: workernodes
#   vars:
#
#   roles:
#     - setup-kube-worker
