---
# tasks file for install-kube

#Disable the Swap

- name: Create a temp directory
  file:
    path: "{{  tempdir  }}"
    state: directory


- name: Disable swap
  command: swapoff -a
  register: swapstatus
  # failed_when: swapstatus.stdout is defined and swapstatus |length > 0
  # changed_when: swapstatus.stdout is not defined or (swapstatus.stdout is defined and swapstatus.stdout == '')


- name: Comment swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.+? sswap s+sw s+.*)$'
    replace: '#  1'
  notify: restart_system


#install docker
# - name: Remove old packages to prepare for Docker installation
#   yum:
#     name: "{{  item  }}"
#     state: removed
#   loop:
#     - docker
#     - docker-client
#     - docker-client-latest
#     - docker-common
#     - docker-latest
#     - docker-latest-logrotate
#     - docker-logrotate
#     - docker-engine
#     - docker-selinux


- name: Install yum updates
  yum: update_cache=yes
  when: ansible_os_family == "RedHat"


- name: Install Utilities required for Docker
  yum:
    name: "{{  item  }}"
    state: latest
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2


- name: Install Docker
  yum:
    name: "{{  item  }}"
    state: latest
  loop:
    - docker


- name: Start Docker
  service:
    name: docker
    state: started


- name: Verify Docker installation
  command: docker --version
  register: dockerversion
  changed_when: dockerversion.stdout | length > 0
  failed_when: dockerversion.stdout | length <= 0


- name: Add Kubernetes yum repository
  yum_repository:
    name: kubernetes
    description: kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes


- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive

# - fail:
#     msg: "Getting a pause...."


- name: Install Kubernetes
  yum:
    name: "{{  item  }}"
    state: latest
    disable_excludes: kubernetes
  loop:
    - kubelet
    - kubeadm
    - kubectl


- name: Enable kubelet
  service:
    name: kubelet
    arguments: --now
    enabled: yes


- name: Remove the temp directory
  file:
    path: "{{  tempdir  }}"
    state: absent


# - name:
